name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd playwright-tests
          npm ci
          npx playwright install --with-deps
      
      - name: Serve site
        run: |
          cd /home/runner/work/test-automation-prep/test-automation-prep/site
          npm install -g http-server
          http-server ./site -p 51515 &
          sleep 3
      
      - name: Run Playwright tests
        run: |
          cd playwright-tests
          npx playwright test
