name: Selenium Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd selenium-tests
          npm ci

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Serve site
        run: |
          npm install -g http-server
          http-server site -p 51515 &
          npx wait-on http://127.0.0.1:51515/site

      - name: Run Selenium test
        run: |
          cd selenium-tests
          node login.test.js
